# Release process
#
# Run `cargo release minor` to publish and create and push a signed tag

pre-release-commit-message = "{{version}}"
push = true
tag = true
tag-name = "{{version}}"
sign-tag = true
sign-commit = true
enable-all-features = true

# Ref: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md
