# Release process
#
# Run `cargo release minor` to publish and create and push a signed tag

push = true
tag = true
sign-tag = true
sign-commit = true
enable-all-features = true
tag-name = "{{version}}"

# Ref: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md
